### ISSUE TITLE
Trying to get property 'lang' of non-object

### ISSUE THREAD

**Issue by vmakarov1720** [panichelpdesk/panichd#14]
![Error](https://user-images.githubusercontent.com/40828720/67953277-16d00d80-fbef-11e9-8ab5-0101f8237364.png)

"Trying to get property 'lang' of non-object (View: C:\xampp\htdocs\laravel\ticketit\vendor\panichd\panichd\src\Views\shared\nav.blade.php) (View: C:\xampp\htdoc ▶"

**Comment by xaviqv** [comment]
Hi,

This error points that $setting var **has not been initialized**. This is done at **PanicHDServiceProvider.php at line 98**, so, if you're getting this error, it probably means that PanicHD service provider is not being loaded.

In addition of this, I see that your local laravel app folder is "ticketit". Either if you have installed a clean PanicHD installation or it is an upgrade from a Ticketit installation, I encourage you to follow the PanicHD installation step by step available in our [readme](https://github.com/panichelpdesk/panichd).

After that, If you ensure to have followed all steps and still getting posted or another error, please specify:
- The error you're getting
- Your Laravel version
- Your PanicHD version
- Is your PanicHD installation an upgrade from Ticketit?

**Comment by hirog85** [comment]
Hi

I have the same problem...

![image](https://user-images.githubusercontent.com/28783768/68246844-f1416a80-0019-11ea-8052-dd50491157e7.png)

how can i load PanicHD ? it's already in my providers in config/app.php.

**Comment by vfic** [comment]
I have the same problem...
![Capture](https://user-images.githubusercontent.com/40229569/68566649-85cc2280-0489-11ea-896d-50f1ff92c16b.PNG)

**Comment by sprklinginfo** [comment]
same error when trying to complete a ticket. In the source file 'Setting.php' I inserted 'dd(gettype($setting))' after line 56, the output does say the variable is an '**object**'. So why it keeps complaining 
Trying to get property 'lang' of non-object...

**Comment by sprklinginfo** [comment]
just created a pull request https://github.com/panichelpdesk/panichd/pull/22 in order to fix this error. Please take a look. It works on my local.

**Comment by Edgarborras94** [comment]
Did you guys tried to un comment this line (49) on Models/Setting.php:
``` //       Cache::flush(); ```
to
```          Cache::flush();```

This may works, depending on your system specs and all :)
