### ISSUE TITLE
Current status: The package installation hasn't finished yet

### ISSUE THREAD

**Issue by vfic** [panichelpdesk/panichd#15]
I got this Error. How  to fix this error? I followed the installation instructions. Thanks
![Capture](https://user-images.githubusercontent.com/40229569/68574450-7904fa00-049c-11ea-89b5-bdf30f6c4651.PNG)

**Comment by xaviqv** [comment]
This page is one of the last steps of PanicHD installation. You should click on the "Install now" button.

The message you have highlighted on the right side is just a contextual one, because if you click on the "Install now" button, the package status will change.

**Comment by vfic** [comment]
I got this error. This is the 5 times i have reinstalled but no one successful :) . Can you make a quick installer like this? https://gitlab.com/balping/ticketit-app
I installed this app. It's work five but it lacks a few features.
**Thank you so much.**
![Capture](https://user-images.githubusercontent.com/40229569/68659906-b9cb4480-056a-11ea-87ff-8b61aef6c759.PNG)
