### ISSUE TITLE
Compatible with laravel 7

### ISSUE THREAD

**Issue by emlycool** [panichelpdesk/panichd#20]
Hi, 
When will it be compatible with laravel 7^?
I need your package for a project but it currently runs on laravel 7. I will like to know if there are plans to upgrade to support lastest Laravel version

**Comment by sprklinginfo** [comment]
Same here...thanks.

**Comment by xaviqv** [comment]
Hi @emlycool and @sprklinginfo . I have just published a new release which is compatible with Laravel 7. Please, let me know If there comes any new issue after upgrading.

https://github.com/panichelpdesk/panichd/releases/tag/v0.19.0

**Comment by emlycool** [comment]
Super thanks @xaviqv will check it out

**Comment by sprklinginfo** [comment]
Great! Thanks, @xaviqv . will try to install it today.
