### ISSUE TITLE
Compatible with laravel 8

### ISSUE THREAD

**Issue by wertex** [panichelpdesk/panichd#28]
Hi!
I have installed laravel 8
then installed laravel/breeze
then ran npm install && npm run dev
artisan migrate
open http://your-laravel-app-URL/panichd
after a short installation: Error Class 'App\User' not found

What can you do next?

**Comment by xaviqv** [comment]
Hello @wertex,

PanicHD Member model extends App\User, which was laravel default User model up to version 7. With a clean Laravel 8 installation with Breeze I've noticed that this is not the [User model default route](https://laravel.com/docs/8.x/authentication#introduction-database-considerations) anymore.

**Updated answer**

Create "App\User.php" file within your Laravel installation with this code:
```
<?php

namespace App;

use App\Models\User as Breeze_User;

class User extends Breeze_User
{
}
?>
```

With the steps **I posted earlier**, you would have a custom PanicHD Member file, and after every PanicHD update, you should update that file manually, which I finally thought it was not a really good idea. This custom file could be useful only if you have really a custom Laravel App configuration.

Please tell me if the issue persists after these instructions.
