### ISSUE TITLE
App\User

### ISSUE THREAD

**Issue by rylxes** [panichelpdesk/panichd#4]
is there any reason why App\User is not configurable , instead of forcing user to follow a structure ?

**Comment by xaviqv** [comment]
Not really. I've thought about having flexibility over users model some times but haven't included it in my tasks list yet. There may be some different ways to achieve that, like the following:

- Include a publishable file "App\PanicHDMember" or similar. Make PanicHD\..\Member.php extend that published file. The published file extends App\User by default.
- Make table name inside PanicHD\..\Member.php a variable that comes from configuration settings with , for example, Setting::grab('member_table')

Do you think is there any better alternative to have this functionality?

**Comment by xaviqv** [comment]
Hi @rylxes , in [today's release](https://github.com/panichelpdesk/panichd/releases) we've added the possibility of creating a custom Member model for PanicHD. After upgrading your installation to v0.12.0 you may follow [the steps we have described in our wiki to do so](https://github.com/panichelpdesk/panichd/wiki/Package-customizations#custom-member-model). Hope you enjoy!

**Comment by rylxes** [comment]
Thats awesome ! , ... i would check it out
