### ISSUE TITLE
jquery error when posting tickets as user

### ISSUE THREAD

**Issue by vasilejianu** [panichelpdesk/panichd#47]
while creating a ticket as user the window doesn't close after clicking add 
I checked the console and it throws a jquery error

jquery-3.4.1.min.js:2 POST http://127.0.0.1:8000/tickets 500 (Internal Server Error)
send @ jquery-3.4.1.min.js:2
ajax @ jquery-3.4.1.min.js:2
ajax_form_submit @ create:380
(anonymous) @ create:361
dispatch @ jquery-3.4.1.min.js:2
v.handle @ jquery-3.4.1.min.js:2

**Comment by xaviqv** [comment]
hello @vasilejianu,

The HTTP error 500 error you're getting is generated in Laravel and not in jquery itself. 

In PanicHD there are some e-mail notifications active by default, but if you don't have all email parameters correctly filled up in your Laravel app or PanicHD or they don't work, when you add a new ticket you will get the error you have specified.

You may even check you Laravel log to view that error traceback. Do check this, please follow these steps:

1. Execute the action that causes this error in your app
2. Open storage\logs in your Laravel app and open today's assigned log file
3. Errors details start with date and time. Look for the instant when you have got the error.
4. Copy these error details in a new comment in this issue

**Comment by vasilejianu** [comment]
[2021-06-23 12:08:35] local.ERROR: Attempt to read property "id" on null {"userId":1,"exception":"[object] (ErrorException(code: 0): Attempt to read property \"id\" on null at F:\\dev\\apex-windows\\vendor\\panichd\\panichd\\src\\Models\\Ticket.php:835)
[stacktrace]
#0 F:\\dev\\apex-windows\\vendor\\panichd\\panichd\\src\\Models\\Ticket.php(835): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'Attempt to read...', 'F:\\\\dev\\\\apex-win...', 835)
#1 F:\\dev\\apex-windows\\vendor\\panichd\\panichd\\src\\Controllers\\TicketsController.php(1578): PanicHD\\PanicHD\\Models\\Ticket->autoSelectAgent()
#2 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Controller.php(54): PanicHD\\PanicHD\\Controllers\\TicketsController->store(Object(Illuminate\\Http\\Request))
#3 F:\\dev\\apex-windows\\vendor\\panichd\\panichd\\src\\Controllers\\TicketsController.php(64): Illuminate\\Routing\\Controller->callAction('store', Array)
#4 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\ControllerDispatcher.php(45): PanicHD\\PanicHD\\Controllers\\TicketsController->callAction('store', Array)
#5 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(254): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(PanicHD\\PanicHD\\Controllers\\TicketsController), 'store')
#6 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(197): Illuminate\\Routing\\Route->runController()
#7 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(695): Illuminate\\Routing\\Route->run()
#8 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#9 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Middleware\\SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#10 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#11 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Auth\\Middleware\\Authenticate.php(44): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#12 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Auth\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#13 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#14 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#15 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#16 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#17 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Session\\Middleware\\StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#18 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Session\\Middleware\\StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))
#19 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#20 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#21 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#22 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#23 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#24 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#25 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(697): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#26 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(672): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#27 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(636): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#28 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(625): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#29 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(166): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#30 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#31 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#32 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#33 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#34 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#35 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#36 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#37 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#38 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#39 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#40 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#41 F:\\dev\\apex-windows\\vendor\\fruitcake\\laravel-cors\\src\\HandleCors.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#42 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#43 F:\\dev\\apex-windows\\vendor\\fideloper\\proxy\\src\\TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#44 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#45 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#46 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(141): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#47 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#48 F:\\dev\\apex-windows\\public\\index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#49 F:\\dev\\apex-windows\\server.php(21): require_once('F:\\\\dev\\\\apex-win...')
#50 {main}
"}

**Comment by xaviqv** [comment]
Hi @vasilejianu,

As you may see at the beginning of your error traceback, it starts in "panichd\src\Models\Ticket.php" at line 835. This line contains:

`$selected_agent_id = $first_admin->id;`

You may use [Laravel tinker](https://laravel.com/docs/8.x/artisan#tinker) to check what do you get in your Laravel app when executing this code:

`\PanicHDMember::admins()->first();`

If you have PanicHD correctly configured, you should get **at least one member account** instance. If I do this in my local app I get:

![image](https://user-images.githubusercontent.com/25639840/123276912-e9438080-d505-11eb-9f7e-5c6217aec7ca.png)

Please share here what do you get with it. If  you get null result, you should review your Laravel users table in your database, and check if your admin account has "panichd_admin" field value "1"

**Comment by vasilejianu** [comment]
ok that makes sense now , its my fault 
Due to testing this in dev and not prod i though ill cheat my way of adding a new user and modified my and only account in db with the flags 0 for admin and agent so no admins were available :)
Thank you very much sir for your help

**Comment by xaviqv** [comment]
Hi @vasilejianu,

I'm glad I could help you. Thanks for your quick response

**Comment by vasilejianu** [comment]
i think now im facing the email problem you mentioned above
disabling the notifications from options menu solves the issue but would like to get this setup properly 
any help in pointing me in the right direction on how to get this working? thanks

[2021-06-24 18:04:15] local.ERROR: Address in mailbox given [] does not comply with RFC 2822, 3.6.2. {"userId":24,"exception":"[object] (Swift_RfcComplianceException(code: 0): Address in mailbox given [] does not comply with RFC 2822, 3.6.2. at F:\\dev\\apex-windows\\vendor\\swiftmailer\\swiftmailer\\lib\\classes\\Swift\\Mime\\Headers\\MailboxHeader.php:355)
[stacktrace]
#0 F:\\dev\\apex-windows\\vendor\\swiftmailer\\swiftmailer\\lib\\classes\\Swift\\Mime\\Headers\\MailboxHeader.php(272): Swift_Mime_Headers_MailboxHeader->assertValidAddress('')
#1 F:\\dev\\apex-windows\\vendor\\swiftmailer\\swiftmailer\\lib\\classes\\Swift\\Mime\\Headers\\MailboxHeader.php(117): Swift_Mime_Headers_MailboxHeader->normalizeMailboxes(Array)
#2 F:\\dev\\apex-windows\\vendor\\swiftmailer\\swiftmailer\\lib\\classes\\Swift\\Mime\\Headers\\MailboxHeader.php(74): Swift_Mime_Headers_MailboxHeader->setNameAddresses(Array)
#3 F:\\dev\\apex-windows\\vendor\\swiftmailer\\swiftmailer\\lib\\classes\\Swift\\Mime\\SimpleMimeEntity.php(600): Swift_Mime_Headers_MailboxHeader->setFieldBodyModel(Array)
#4 F:\\dev\\apex-windows\\vendor\\swiftmailer\\swiftmailer\\lib\\classes\\Swift\\Mime\\SimpleMessage.php(213): Swift_Mime_SimpleMimeEntity->setHeaderFieldModel('From', Array)
#5 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Mail\\Message.php(50): Swift_Mime_SimpleMessage->setFrom(Array, 'Laravel')
#6 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Mail\\Mailable.php(355): Illuminate\\Mail\\Message->from(NULL, 'Laravel')
#7 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Mail\\Mailable.php(181): Illuminate\\Mail\\Mailable->buildFrom(Object(Illuminate\\Mail\\Message))
#8 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Mail\\Mailer.php(271): Illuminate\\Mail\\Mailable->Illuminate\\Mail\\{closure}(Object(Illuminate\\Mail\\Message))
#9 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Mail\\Mailable.php(186): Illuminate\\Mail\\Mailer->send('panichd::emails...', Array, Object(Closure))
#10 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\Traits\\Localizable.php(19): Illuminate\\Mail\\Mailable->Illuminate\\Mail\\{closure}()
#11 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Mail\\Mailable.php(187): Illuminate\\Mail\\Mailable->withLocale(NULL, Object(Closure))
#12 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Mail\\Mailer.php(304): Illuminate\\Mail\\Mailable->send(Object(Illuminate\\Mail\\Mailer))
#13 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Mail\\Mailer.php(258): Illuminate\\Mail\\Mailer->sendMailable(Object(PanicHD\\PanicHD\\Mail\\PanicHDNotification))
#14 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Mail\\PendingMail.php(121): Illuminate\\Mail\\Mailer->send(Object(PanicHD\\PanicHD\\Mail\\PanicHDNotification))
#15 F:\\dev\\apex-windows\\vendor\\panichd\\panichd\\src\\Controllers\\NotificationsController.php(434): Illuminate\\Mail\\PendingMail->send(Object(PanicHD\\PanicHD\\Mail\\PanicHDNotification))
#16 F:\\dev\\apex-windows\\vendor\\panichd\\panichd\\src\\Controllers\\NotificationsController.php(225): PanicHD\\PanicHD\\Controllers\\NotificationsController->sendNotification(Array, Array)
#17 F:\\dev\\apex-windows\\vendor\\panichd\\panichd\\src\\PanicHDServiceProvider.php(269): PanicHD\\PanicHD\\Controllers\\NotificationsController->newComment(Object(PanicHD\\PanicHD\\Models\\Comment), Object(Illuminate\\Http\\Request))
#18 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Events\\Dispatcher.php(392): PanicHD\\PanicHD\\PanicHDServiceProvider->PanicHD\\PanicHD\\{closure}(Object(PanicHD\\PanicHD\\Events\\CommentCreated))
#19 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Events\\Dispatcher.php(237): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}('PanicHD\\\\PanicHD...', Array)
#20 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\helpers.php(450): Illuminate\\Events\\Dispatcher->dispatch('PanicHD\\\\PanicHD...')
#21 F:\\dev\\apex-windows\\vendor\\panichd\\panichd\\src\\Controllers\\CommentsController.php(217): event(Object(PanicHD\\PanicHD\\Events\\CommentCreated))
#22 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Controller.php(54): PanicHD\\PanicHD\\Controllers\\CommentsController->store(Object(Illuminate\\Http\\Request))
#23 F:\\dev\\apex-windows\\vendor\\panichd\\panichd\\src\\Controllers\\CommentsController.php(36): Illuminate\\Routing\\Controller->callAction('store', Array)
#24 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\ControllerDispatcher.php(45): PanicHD\\PanicHD\\Controllers\\CommentsController->callAction('store', Array)
#25 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(254): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(PanicHD\\PanicHD\\Controllers\\CommentsController), 'store')
#26 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(197): Illuminate\\Routing\\Route->runController()
#27 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(695): Illuminate\\Routing\\Route->run()
#28 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#29 F:\\dev\\apex-windows\\vendor\\panichd\\panichd\\src\\Middleware\\UserAccessMiddleware.php(35): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#30 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): PanicHD\\PanicHD\\Middleware\\UserAccessMiddleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#31 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Middleware\\SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#32 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#33 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Auth\\Middleware\\Authenticate.php(44): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#34 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Auth\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#35 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#36 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#37 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#38 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#39 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Session\\Middleware\\StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#40 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Session\\Middleware\\StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))
#41 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#42 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#43 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#44 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#45 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#46 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#47 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(697): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#48 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(672): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#49 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(636): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#50 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(625): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#51 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(166): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#52 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#53 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#54 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#55 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#56 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#57 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#58 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#59 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#60 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#61 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#62 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#63 F:\\dev\\apex-windows\\vendor\\fruitcake\\laravel-cors\\src\\HandleCors.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#64 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#65 F:\\dev\\apex-windows\\vendor\\fideloper\\proxy\\src\\TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#66 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#67 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#68 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(141): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#69 F:\\dev\\apex-windows\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#70 F:\\dev\\apex-windows\\public\\index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#71 F:\\dev\\apex-windows\\server.php(21): require_once('F:\\\\dev\\\\apex-win...')
#72 {main}
"}
