### ISSUE TITLE
Error during Install

### ISSUE THREAD

**Issue by JuanAdamuz** [panichelpdesk/panichd#6]
Symfony \ Component \ Debug \ Exception \ FatalErrorException (E_UNKNOWN)
Cannot make non static method App\User::isAdmin() static in class PanicHD\PanicHD\Models\Member

**Comment by JuanAdamuz** [comment]
C:\Users\IES TRASSIERRA\Documents\GitHub\pcu\vendor\panichd\panichd\src\Models\Member.php
    
    /*
     * Get member related departments in Department hierarchy
     *
     * For a main department: Returns self + all descendants
     * For descendant: Returns self + ancestor
     *
     * @Return collection
    */
    public function getRelatedDepartments()
    {
        $member_department = $this->department()->get();
        
        if ($this->department()->first()->is_main()){
            return $member_department->merge($this->department()->first()->descendants()->get());
        }else{
            return $member_department->merge($this->department()->first()->ancestor()->get());
        }
    }
}
 
Arguments
"Cannot make non static method App\User::isAdmin() static in class PanicHD\PanicHD\Models\Member"

**Comment by xaviqv** [comment]
Hola @JuanAdamuz ,
Are you still having this issue? I've just released [an update of the package](https://github.com/panichelpdesk/panichd/releases/tag/V0.14.0). It doesn't have any modification of the installation files, but anyway, could you please do a fresh install of current release and confirm if you still get this error? Or if you solved it before i'd be glad to know how.

In the case of a fresh install where you still have any trouble, please tell us your Laravel version. Thanks for your feedback!

**Comment by JuanAdamuz** [comment]
Sorry for the late response...

I have just updated my laravel istallation to 5.7 and still have the issue:


In Member.php line 9:

Cannot make non static method App\User::isAdmin() static in class PanicHD\PanicHD\Models\Member


The thing is that i already have a IsAdmin() method in my USer model for my framework, this could be the problem?

**Comment by JuanAdamuz** [comment]
Yep it was that now the routes doesnt work I enterthe /panichd and I get 404 error

**Comment by JuanAdamuz** [comment]
Solved, putting Kordy\Ticketit\TicketitServiceProvider::class, just before App\Providers\RouteServiceProvider::class solved it. Thanks!
