### ISSUE TITLE
Change master Template

### ISSUE THREAD

**Issue by JuanAdamuz** [panichelpdesk/panichd#8]
How can I reference my master view? Its on resources\views\layers\header.blade.php And its on materialize css Its going to affect bootstrap framework on ticket system?

**Comment by xaviqv** [comment]
Hi, Hope you already found out the solution.

The default master template in PanicHD is panichd::master, which is located in the package's src/views/ folder. To change this behavior you have two options:

- Customize master template
- Use other view as master template

**Customize master template**
You may create a new file in you Laravel App resources/views/vendor/panichd folder with filename "master.blade.php". You can create it from scratch or copy and edit the original PanicHD master view.
This is the same behavior you may take advantage of as with any other package installed in your Laravel App.

**Use other view as master template**

1. Access PanicHD Configuration Settings menu (it opens in the initial tab)
2. Locate and edit "master_template" setting
3. Specify the name of a Laravel valid view that exists in your Laravel app.

If anyone gets in trouble after updating master_template, you may edit it **via database** at the panichd_settings table. The setting name equals slug field.
